modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"

[[mods]]
modId="myfirstmod"
version="${version}"
displayName="My first mod"
description='''
	the first mod i try to make.
'''

[[dependencies.myfirstmod]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.myfirstmod]]
    modId="minecraft"
    mandatory=true
	versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
